/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class LosCheetosQuickfixProvider extends DefaultQuickfixProvider {
}
