/*
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import losCheetos.ui.internal.LosCheetosActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LosCheetosExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LosCheetosActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LosCheetosActivator.getInstance().getInjector(LosCheetosActivator.EDU_UPB_LP_ISC_LOSCHEETOS);
	}
	
}
