/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.ui.contentassist;

import edu.upb.lp.isc.ui.contentassist.AbstractLosCheetosProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LosCheetosProposalProvider extends AbstractLosCheetosProposalProvider {
}
