/*
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLosCheetosValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.upb.lp.isc.losCheetos.LosCheetosPackage.eINSTANCE);
		return result;
	}
	
}
