/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LosCheetosIdeSetup /* implements LosCheetosStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nLosCheetosRuntimeModule cannot be resolved.");
  }
}
