/*
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.parser.antlr;

import com.google.inject.Inject;
import edu.upb.lp.isc.parser.antlr.internal.InternalLosCheetosParser;
import edu.upb.lp.isc.services.LosCheetosGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LosCheetosParser extends AbstractAntlrParser {

	@Inject
	private LosCheetosGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLosCheetosParser createParser(XtextTokenStream stream) {
		return new InternalLosCheetosParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MyRacketProgram";
	}

	public LosCheetosGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LosCheetosGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
