/*
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LosCheetosAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/upb/lp/isc/parser/antlr/internal/InternalLosCheetos.tokens");
	}
}
