/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos.impl;

import edu.upb.lp.isc.losCheetos.Expression;
import edu.upb.lp.isc.losCheetos.LosCheetosPackage;
import edu.upb.lp.isc.losCheetos.StrAppExpression;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Str App Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl#getStr1 <em>Str1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl#getStr2 <em>Str2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StrAppExpressionImpl extends StrOpExpressionImpl implements StrAppExpression
{
  /**
   * The cached value of the '{@link #getStr1() <em>Str1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr1()
   * @generated
   * @ordered
   */
  protected Expression str1;

  /**
   * The cached value of the '{@link #getStr2() <em>Str2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr2()
   * @generated
   * @ordered
   */
  protected Expression str2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrAppExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LosCheetosPackage.Literals.STR_APP_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getStr1()
  {
    return str1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStr1(Expression newStr1, NotificationChain msgs)
  {
    Expression oldStr1 = str1;
    str1 = newStr1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosCheetosPackage.STR_APP_EXPRESSION__STR1, oldStr1, newStr1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStr1(Expression newStr1)
  {
    if (newStr1 != str1)
    {
      NotificationChain msgs = null;
      if (str1 != null)
        msgs = ((InternalEObject)str1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosCheetosPackage.STR_APP_EXPRESSION__STR1, null, msgs);
      if (newStr1 != null)
        msgs = ((InternalEObject)newStr1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosCheetosPackage.STR_APP_EXPRESSION__STR1, null, msgs);
      msgs = basicSetStr1(newStr1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosCheetosPackage.STR_APP_EXPRESSION__STR1, newStr1, newStr1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getStr2()
  {
    return str2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStr2(Expression newStr2, NotificationChain msgs)
  {
    Expression oldStr2 = str2;
    str2 = newStr2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LosCheetosPackage.STR_APP_EXPRESSION__STR2, oldStr2, newStr2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStr2(Expression newStr2)
  {
    if (newStr2 != str2)
    {
      NotificationChain msgs = null;
      if (str2 != null)
        msgs = ((InternalEObject)str2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LosCheetosPackage.STR_APP_EXPRESSION__STR2, null, msgs);
      if (newStr2 != null)
        msgs = ((InternalEObject)newStr2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LosCheetosPackage.STR_APP_EXPRESSION__STR2, null, msgs);
      msgs = basicSetStr2(newStr2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LosCheetosPackage.STR_APP_EXPRESSION__STR2, newStr2, newStr2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LosCheetosPackage.STR_APP_EXPRESSION__STR1:
        return basicSetStr1(null, msgs);
      case LosCheetosPackage.STR_APP_EXPRESSION__STR2:
        return basicSetStr2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LosCheetosPackage.STR_APP_EXPRESSION__STR1:
        return getStr1();
      case LosCheetosPackage.STR_APP_EXPRESSION__STR2:
        return getStr2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LosCheetosPackage.STR_APP_EXPRESSION__STR1:
        setStr1((Expression)newValue);
        return;
      case LosCheetosPackage.STR_APP_EXPRESSION__STR2:
        setStr2((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LosCheetosPackage.STR_APP_EXPRESSION__STR1:
        setStr1((Expression)null);
        return;
      case LosCheetosPackage.STR_APP_EXPRESSION__STR2:
        setStr2((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LosCheetosPackage.STR_APP_EXPRESSION__STR1:
        return str1 != null;
      case LosCheetosPackage.STR_APP_EXPRESSION__STR2:
        return str2 != null;
    }
    return super.eIsSet(featureID);
  }

} //StrAppExpressionImpl
