/*
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LosCheetosStandaloneSetup extends LosCheetosStandaloneSetupGenerated {

	def static void doSetup() {
		new LosCheetosStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
