/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arith Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ArithExpression#getOp <em>Op</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ArithExpression#getArg1 <em>Arg1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ArithExpression#getOargs <em>Oargs</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getArithExpression()
 * @model
 * @generated
 */
public interface ArithExpression extends NumberExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getArithExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.ArithExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg1</em>' containment reference.
   * @see #setArg1(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getArithExpression_Arg1()
   * @model containment="true"
   * @generated
   */
  Expression getArg1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.ArithExpression#getArg1 <em>Arg1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg1</em>' containment reference.
   * @see #getArg1()
   * @generated
   */
  void setArg1(Expression value);

  /**
   * Returns the value of the '<em><b>Oargs</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.losCheetos.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oargs</em>' containment reference list.
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getArithExpression_Oargs()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getOargs();

} // ArithExpression
