/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Num Comp Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getComp <em>Comp</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE1 <em>E1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE2 <em>E2</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getBoolNumCompExpression()
 * @model
 * @generated
 */
public interface BoolNumCompExpression extends BoolExpression
{
  /**
   * Returns the value of the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' attribute.
   * @see #setComp(String)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getBoolNumCompExpression_Comp()
   * @model
   * @generated
   */
  String getComp();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getComp <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' attribute.
   * @see #getComp()
   * @generated
   */
  void setComp(String value);

  /**
   * Returns the value of the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E1</em>' containment reference.
   * @see #setE1(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getBoolNumCompExpression_E1()
   * @model containment="true"
   * @generated
   */
  Expression getE1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE1 <em>E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E1</em>' containment reference.
   * @see #getE1()
   * @generated
   */
  void setE1(Expression value);

  /**
   * Returns the value of the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E2</em>' containment reference.
   * @see #setE2(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getBoolNumCompExpression_E2()
   * @model containment="true"
   * @generated
   */
  Expression getE2();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE2 <em>E2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E2</em>' containment reference.
   * @see #getE2()
   * @generated
   */
  void setE2(Expression value);

} // BoolNumCompExpression
