/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.CompExpression#getReal <em>Real</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.CompExpression#getImag <em>Imag</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getCompExpression()
 * @model
 * @generated
 */
public interface CompExpression extends NumberExpression
{
  /**
   * Returns the value of the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Real</em>' attribute.
   * @see #setReal(int)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getCompExpression_Real()
   * @model
   * @generated
   */
  int getReal();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.CompExpression#getReal <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Real</em>' attribute.
   * @see #getReal()
   * @generated
   */
  void setReal(int value);

  /**
   * Returns the value of the '<em><b>Imag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imag</em>' attribute.
   * @see #setImag(int)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getCompExpression_Imag()
   * @model
   * @generated
   */
  int getImag();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.CompExpression#getImag <em>Imag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imag</em>' attribute.
   * @see #getImag()
   * @generated
   */
  void setImag(int value);

} // CompExpression
