/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cons Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ConsExpression#getExpr <em>Expr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ConsExpression#getList <em>List</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getConsExpression()
 * @model
 * @generated
 */
public interface ConsExpression extends ListOpExpression
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getConsExpression_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.ConsExpression#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(ListExpression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getConsExpression_List()
   * @model containment="true"
   * @generated
   */
  ListExpression getList();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.ConsExpression#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(ListExpression value);

} // ConsExpression
