/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frac Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.FracExpression#getNum <em>Num</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.FracExpression#getDec <em>Dec</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getFracExpression()
 * @model
 * @generated
 */
public interface FracExpression extends NumberExpression
{
  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getFracExpression_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.FracExpression#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' attribute.
   * @see #setDec(int)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getFracExpression_Dec()
   * @model
   * @generated
   */
  int getDec();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.FracExpression#getDec <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' attribute.
   * @see #getDec()
   * @generated
   */
  void setDec(int value);

} // FracExpression
