/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Length Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.LengthExpression#getList <em>List</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getLengthExpression()
 * @model
 * @generated
 */
public interface LengthExpression extends ListOpExpression
{
  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getLengthExpression_List()
   * @model containment="true"
   * @generated
   */
  Expression getList();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.LengthExpression#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(Expression value);

} // LengthExpression
