/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.ListExpression#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getListExpression()
 * @model
 * @generated
 */
public interface ListExpression extends SimpleExpression
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.losCheetos.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getListExpression_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // ListExpression
