/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.losCheetos.LosCheetosFactory
 * @model kind="package"
 * @generated
 */
public interface LosCheetosPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "losCheetos";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/LosCheetos";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "losCheetos";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LosCheetosPackage eINSTANCE = edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.MyRacketProgramImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getMyRacketProgram()
   * @generated
   */
  int MY_RACKET_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Defines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__DEFINES = 0;

  /**
   * The feature id for the '<em><b>Executions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM__EXECUTIONS = 1;

  /**
   * The number of structural features of the '<em>My Racket Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_RACKET_PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.DefineImpl <em>Define</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.DefineImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getDefine()
   * @generated
   */
  int DEFINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE__BODY = 2;

  /**
   * The number of structural features of the '<em>Define</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.SimpleExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getSimpleExpression()
   * @generated
   */
  int SIMPLE_EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Simple Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.NumberExpressionImpl <em>Number Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.NumberExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getNumberExpression()
   * @generated
   */
  int NUMBER_EXPRESSION = 4;

  /**
   * The number of structural features of the '<em>Number Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.IntExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION__VALUE = NUMBER_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = NUMBER_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.DoubleExpressionImpl <em>Double Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.DoubleExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getDoubleExpression()
   * @generated
   */
  int DOUBLE_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_EXPRESSION__INT = NUMBER_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_EXPRESSION__DEC = NUMBER_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Double Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_EXPRESSION_FEATURE_COUNT = NUMBER_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.FracExpressionImpl <em>Frac Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.FracExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getFracExpression()
   * @generated
   */
  int FRAC_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAC_EXPRESSION__NUM = NUMBER_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAC_EXPRESSION__DEC = NUMBER_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Frac Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAC_EXPRESSION_FEATURE_COUNT = NUMBER_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.CompExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCompExpression()
   * @generated
   */
  int COMP_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__REAL = NUMBER_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Imag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__IMAG = NUMBER_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comp Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION_FEATURE_COUNT = NUMBER_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolExpressionImpl <em>Bool Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.BoolExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolExpression()
   * @generated
   */
  int BOOL_EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Bool Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.BoolConstantImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = BOOL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = BOOL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolNumCompExpressionImpl <em>Bool Num Comp Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.BoolNumCompExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolNumCompExpression()
   * @generated
   */
  int BOOL_NUM_COMP_EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_NUM_COMP_EXPRESSION__COMP = BOOL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_NUM_COMP_EXPRESSION__E1 = BOOL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_NUM_COMP_EXPRESSION__E2 = BOOL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Bool Num Comp Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_NUM_COMP_EXPRESSION_FEATURE_COUNT = BOOL_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolCompExpressionImpl <em>Bool Comp Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.BoolCompExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolCompExpression()
   * @generated
   */
  int BOOL_COMP_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_COMP_EXPRESSION__E1 = BOOL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_COMP_EXPRESSION__E2 = BOOL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bool Comp Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_COMP_EXPRESSION_FEATURE_COUNT = BOOL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.StrExpressionImpl <em>Str Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.StrExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrExpression()
   * @generated
   */
  int STR_EXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_EXPRESSION__VALUE = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Str Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ListExpressionImpl <em>List Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ListExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getListExpression()
   * @generated
   */
  int LIST_EXPRESSION = 14;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPRESSION__ARGS = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.PrintExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getPrintExpression()
   * @generated
   */
  int PRINT_EXPRESSION = 15;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION__EXPR = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ListOpExpressionImpl <em>List Op Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ListOpExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getListOpExpression()
   * @generated
   */
  int LIST_OP_EXPRESSION = 16;

  /**
   * The number of structural features of the '<em>List Op Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_OP_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.CarExpressionImpl <em>Car Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.CarExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCarExpression()
   * @generated
   */
  int CAR_EXPRESSION = 17;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAR_EXPRESSION__LIST = LIST_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Car Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAR_EXPRESSION_FEATURE_COUNT = LIST_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.CdrExpressionImpl <em>Cdr Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.CdrExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCdrExpression()
   * @generated
   */
  int CDR_EXPRESSION = 18;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDR_EXPRESSION__LIST = LIST_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cdr Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDR_EXPRESSION_FEATURE_COUNT = LIST_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.LengthExpressionImpl <em>Length Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.LengthExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getLengthExpression()
   * @generated
   */
  int LENGTH_EXPRESSION = 19;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_EXPRESSION__LIST = LIST_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Length Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_EXPRESSION_FEATURE_COUNT = LIST_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.EmptyExpressionImpl <em>Empty Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.EmptyExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getEmptyExpression()
   * @generated
   */
  int EMPTY_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPTY_EXPRESSION__LIST = LIST_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Empty Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPTY_EXPRESSION_FEATURE_COUNT = LIST_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ConsExpressionImpl <em>Cons Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ConsExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getConsExpression()
   * @generated
   */
  int CONS_EXPRESSION = 21;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONS_EXPRESSION__EXPR = LIST_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONS_EXPRESSION__LIST = LIST_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cons Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONS_EXPRESSION_FEATURE_COUNT = LIST_OP_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.StrOpExpressionImpl <em>Str Op Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.StrOpExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrOpExpression()
   * @generated
   */
  int STR_OP_EXPRESSION = 22;

  /**
   * The number of structural features of the '<em>Str Op Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_OP_EXPRESSION_FEATURE_COUNT = SIMPLE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.StrLenExpressionImpl <em>Str Len Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.StrLenExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrLenExpression()
   * @generated
   */
  int STR_LEN_EXPRESSION = 23;

  /**
   * The feature id for the '<em><b>Str</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_LEN_EXPRESSION__STR = STR_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Str Len Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_LEN_EXPRESSION_FEATURE_COUNT = STR_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl <em>Str App Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrAppExpression()
   * @generated
   */
  int STR_APP_EXPRESSION = 24;

  /**
   * The feature id for the '<em><b>Str1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_APP_EXPRESSION__STR1 = STR_OP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Str2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_APP_EXPRESSION__STR2 = STR_OP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Str App Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_APP_EXPRESSION_FEATURE_COUNT = STR_OP_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ParamCallExpressionImpl <em>Param Call Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ParamCallExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getParamCallExpression()
   * @generated
   */
  int PARAM_CALL_EXPRESSION = 25;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_CALL_EXPRESSION__PARAM = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Param Call Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_CALL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.ArithExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getArithExpression()
   * @generated
   */
  int ARITH_EXPRESSION = 26;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__OP = NUMBER_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__ARG1 = NUMBER_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Oargs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__OARGS = NUMBER_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Arith Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION_FEATURE_COUNT = NUMBER_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.IfExpressionImpl <em>If Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.IfExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getIfExpression()
   * @generated
   */
  int IF_EXPRESSION = 27;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__COND = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__THEN = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION__ELSE = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.FunctionCallExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getFunctionCallExpression()
   * @generated
   */
  int FUNCTION_CALL_EXPRESSION = 28;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__FUNCTION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION__ARGS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function Call Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.losCheetos.impl.WhileExpressionImpl <em>While Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.losCheetos.impl.WhileExpressionImpl
   * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getWhileExpression()
   * @generated
   */
  int WHILE_EXPRESSION = 29;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__COND = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Do</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__DO = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.MyRacketProgram <em>My Racket Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Racket Program</em>'.
   * @see edu.upb.lp.isc.losCheetos.MyRacketProgram
   * @generated
   */
  EClass getMyRacketProgram();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.MyRacketProgram#getDefines <em>Defines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defines</em>'.
   * @see edu.upb.lp.isc.losCheetos.MyRacketProgram#getDefines()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Defines();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.MyRacketProgram#getExecutions <em>Executions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Executions</em>'.
   * @see edu.upb.lp.isc.losCheetos.MyRacketProgram#getExecutions()
   * @see #getMyRacketProgram()
   * @generated
   */
  EReference getMyRacketProgram_Executions();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.Define <em>Define</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Define</em>'.
   * @see edu.upb.lp.isc.losCheetos.Define
   * @generated
   */
  EClass getDefine();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.Define#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.losCheetos.Define#getName()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Name();

  /**
   * Returns the meta object for the attribute list '{@link edu.upb.lp.isc.losCheetos.Define#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see edu.upb.lp.isc.losCheetos.Define#getParams()
   * @see #getDefine()
   * @generated
   */
  EAttribute getDefine_Params();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.Define#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see edu.upb.lp.isc.losCheetos.Define#getBody()
   * @see #getDefine()
   * @generated
   */
  EReference getDefine_Body();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.SimpleExpression <em>Simple Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.SimpleExpression
   * @generated
   */
  EClass getSimpleExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.NumberExpression <em>Number Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.NumberExpression
   * @generated
   */
  EClass getNumberExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.IntExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.losCheetos.IntExpression#getValue()
   * @see #getIntExpression()
   * @generated
   */
  EAttribute getIntExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.DoubleExpression <em>Double Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.DoubleExpression
   * @generated
   */
  EClass getDoubleExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.DoubleExpression#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see edu.upb.lp.isc.losCheetos.DoubleExpression#getInt()
   * @see #getDoubleExpression()
   * @generated
   */
  EAttribute getDoubleExpression_Int();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.DoubleExpression#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dec</em>'.
   * @see edu.upb.lp.isc.losCheetos.DoubleExpression#getDec()
   * @see #getDoubleExpression()
   * @generated
   */
  EAttribute getDoubleExpression_Dec();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.FracExpression <em>Frac Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frac Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.FracExpression
   * @generated
   */
  EClass getFracExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.FracExpression#getNum <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num</em>'.
   * @see edu.upb.lp.isc.losCheetos.FracExpression#getNum()
   * @see #getFracExpression()
   * @generated
   */
  EAttribute getFracExpression_Num();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.FracExpression#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dec</em>'.
   * @see edu.upb.lp.isc.losCheetos.FracExpression#getDec()
   * @see #getFracExpression()
   * @generated
   */
  EAttribute getFracExpression_Dec();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.CompExpression <em>Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comp Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.CompExpression
   * @generated
   */
  EClass getCompExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.CompExpression#getReal <em>Real</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Real</em>'.
   * @see edu.upb.lp.isc.losCheetos.CompExpression#getReal()
   * @see #getCompExpression()
   * @generated
   */
  EAttribute getCompExpression_Real();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.CompExpression#getImag <em>Imag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imag</em>'.
   * @see edu.upb.lp.isc.losCheetos.CompExpression#getImag()
   * @see #getCompExpression()
   * @generated
   */
  EAttribute getCompExpression_Imag();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.BoolExpression <em>Bool Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolExpression
   * @generated
   */
  EClass getBoolExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.BoolConstant#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolConstant#isValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression <em>Bool Num Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Num Comp Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolNumCompExpression
   * @generated
   */
  EClass getBoolNumCompExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getComp <em>Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comp</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getComp()
   * @see #getBoolNumCompExpression()
   * @generated
   */
  EAttribute getBoolNumCompExpression_Comp();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE1()
   * @see #getBoolNumCompExpression()
   * @generated
   */
  EReference getBoolNumCompExpression_E1();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolNumCompExpression#getE2()
   * @see #getBoolNumCompExpression()
   * @generated
   */
  EReference getBoolNumCompExpression_E2();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.BoolCompExpression <em>Bool Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Comp Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolCompExpression
   * @generated
   */
  EClass getBoolCompExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.BoolCompExpression#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolCompExpression#getE1()
   * @see #getBoolCompExpression()
   * @generated
   */
  EReference getBoolCompExpression_E1();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.BoolCompExpression#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see edu.upb.lp.isc.losCheetos.BoolCompExpression#getE2()
   * @see #getBoolCompExpression()
   * @generated
   */
  EReference getBoolCompExpression_E2();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.StrExpression <em>Str Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Str Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrExpression
   * @generated
   */
  EClass getStrExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.StrExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrExpression#getValue()
   * @see #getStrExpression()
   * @generated
   */
  EAttribute getStrExpression_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.ListExpression <em>List Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.ListExpression
   * @generated
   */
  EClass getListExpression();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.ListExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.losCheetos.ListExpression#getArgs()
   * @see #getListExpression()
   * @generated
   */
  EReference getListExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.PrintExpression <em>Print Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.PrintExpression
   * @generated
   */
  EClass getPrintExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.PrintExpression#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see edu.upb.lp.isc.losCheetos.PrintExpression#getExpr()
   * @see #getPrintExpression()
   * @generated
   */
  EReference getPrintExpression_Expr();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.ListOpExpression <em>List Op Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Op Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.ListOpExpression
   * @generated
   */
  EClass getListOpExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.CarExpression <em>Car Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Car Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.CarExpression
   * @generated
   */
  EClass getCarExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.CarExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.losCheetos.CarExpression#getList()
   * @see #getCarExpression()
   * @generated
   */
  EReference getCarExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.CdrExpression <em>Cdr Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cdr Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.CdrExpression
   * @generated
   */
  EClass getCdrExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.CdrExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.losCheetos.CdrExpression#getList()
   * @see #getCdrExpression()
   * @generated
   */
  EReference getCdrExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.LengthExpression <em>Length Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Length Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.LengthExpression
   * @generated
   */
  EClass getLengthExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.LengthExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.losCheetos.LengthExpression#getList()
   * @see #getLengthExpression()
   * @generated
   */
  EReference getLengthExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.EmptyExpression <em>Empty Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Empty Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.EmptyExpression
   * @generated
   */
  EClass getEmptyExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.EmptyExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.losCheetos.EmptyExpression#getList()
   * @see #getEmptyExpression()
   * @generated
   */
  EReference getEmptyExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.ConsExpression <em>Cons Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cons Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.ConsExpression
   * @generated
   */
  EClass getConsExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.ConsExpression#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see edu.upb.lp.isc.losCheetos.ConsExpression#getExpr()
   * @see #getConsExpression()
   * @generated
   */
  EReference getConsExpression_Expr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.ConsExpression#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see edu.upb.lp.isc.losCheetos.ConsExpression#getList()
   * @see #getConsExpression()
   * @generated
   */
  EReference getConsExpression_List();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.StrOpExpression <em>Str Op Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Str Op Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrOpExpression
   * @generated
   */
  EClass getStrOpExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.StrLenExpression <em>Str Len Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Str Len Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrLenExpression
   * @generated
   */
  EClass getStrLenExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.StrLenExpression#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Str</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrLenExpression#getStr()
   * @see #getStrLenExpression()
   * @generated
   */
  EReference getStrLenExpression_Str();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.StrAppExpression <em>Str App Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Str App Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrAppExpression
   * @generated
   */
  EClass getStrAppExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr1 <em>Str1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Str1</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrAppExpression#getStr1()
   * @see #getStrAppExpression()
   * @generated
   */
  EReference getStrAppExpression_Str1();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr2 <em>Str2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Str2</em>'.
   * @see edu.upb.lp.isc.losCheetos.StrAppExpression#getStr2()
   * @see #getStrAppExpression()
   * @generated
   */
  EReference getStrAppExpression_Str2();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.ParamCallExpression <em>Param Call Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Call Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.ParamCallExpression
   * @generated
   */
  EClass getParamCallExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.ParamCallExpression#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see edu.upb.lp.isc.losCheetos.ParamCallExpression#getParam()
   * @see #getParamCallExpression()
   * @generated
   */
  EAttribute getParamCallExpression_Param();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.ArithExpression <em>Arith Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.ArithExpression
   * @generated
   */
  EClass getArithExpression();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.losCheetos.ArithExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.losCheetos.ArithExpression#getOp()
   * @see #getArithExpression()
   * @generated
   */
  EAttribute getArithExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.ArithExpression#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg1</em>'.
   * @see edu.upb.lp.isc.losCheetos.ArithExpression#getArg1()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Arg1();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.ArithExpression#getOargs <em>Oargs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Oargs</em>'.
   * @see edu.upb.lp.isc.losCheetos.ArithExpression#getOargs()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Oargs();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.IfExpression <em>If Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.IfExpression
   * @generated
   */
  EClass getIfExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.IfExpression#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see edu.upb.lp.isc.losCheetos.IfExpression#getCond()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Cond();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.IfExpression#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see edu.upb.lp.isc.losCheetos.IfExpression#getThen()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Then();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.IfExpression#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see edu.upb.lp.isc.losCheetos.IfExpression#getElse()
   * @see #getIfExpression()
   * @generated
   */
  EReference getIfExpression_Else();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.FunctionCallExpression <em>Function Call Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.FunctionCallExpression
   * @generated
   */
  EClass getFunctionCallExpression();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.losCheetos.FunctionCallExpression#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see edu.upb.lp.isc.losCheetos.FunctionCallExpression#getFunction()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Function();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.FunctionCallExpression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see edu.upb.lp.isc.losCheetos.FunctionCallExpression#getArgs()
   * @see #getFunctionCallExpression()
   * @generated
   */
  EReference getFunctionCallExpression_Args();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.losCheetos.WhileExpression <em>While Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Expression</em>'.
   * @see edu.upb.lp.isc.losCheetos.WhileExpression
   * @generated
   */
  EClass getWhileExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.losCheetos.WhileExpression#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see edu.upb.lp.isc.losCheetos.WhileExpression#getCond()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_Cond();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.losCheetos.WhileExpression#getDo <em>Do</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Do</em>'.
   * @see edu.upb.lp.isc.losCheetos.WhileExpression#getDo()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_Do();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LosCheetosFactory getLosCheetosFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.MyRacketProgramImpl <em>My Racket Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.MyRacketProgramImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getMyRacketProgram()
     * @generated
     */
    EClass MY_RACKET_PROGRAM = eINSTANCE.getMyRacketProgram();

    /**
     * The meta object literal for the '<em><b>Defines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__DEFINES = eINSTANCE.getMyRacketProgram_Defines();

    /**
     * The meta object literal for the '<em><b>Executions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_RACKET_PROGRAM__EXECUTIONS = eINSTANCE.getMyRacketProgram_Executions();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.DefineImpl <em>Define</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.DefineImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getDefine()
     * @generated
     */
    EClass DEFINE = eINSTANCE.getDefine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__NAME = eINSTANCE.getDefine_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINE__PARAMS = eINSTANCE.getDefine_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINE__BODY = eINSTANCE.getDefine_Body();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.SimpleExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getSimpleExpression()
     * @generated
     */
    EClass SIMPLE_EXPRESSION = eINSTANCE.getSimpleExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.NumberExpressionImpl <em>Number Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.NumberExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getNumberExpression()
     * @generated
     */
    EClass NUMBER_EXPRESSION = eINSTANCE.getNumberExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.IntExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_EXPRESSION__VALUE = eINSTANCE.getIntExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.DoubleExpressionImpl <em>Double Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.DoubleExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getDoubleExpression()
     * @generated
     */
    EClass DOUBLE_EXPRESSION = eINSTANCE.getDoubleExpression();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE_EXPRESSION__INT = eINSTANCE.getDoubleExpression_Int();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE_EXPRESSION__DEC = eINSTANCE.getDoubleExpression_Dec();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.FracExpressionImpl <em>Frac Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.FracExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getFracExpression()
     * @generated
     */
    EClass FRAC_EXPRESSION = eINSTANCE.getFracExpression();

    /**
     * The meta object literal for the '<em><b>Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAC_EXPRESSION__NUM = eINSTANCE.getFracExpression_Num();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAC_EXPRESSION__DEC = eINSTANCE.getFracExpression_Dec();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.CompExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCompExpression()
     * @generated
     */
    EClass COMP_EXPRESSION = eINSTANCE.getCompExpression();

    /**
     * The meta object literal for the '<em><b>Real</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMP_EXPRESSION__REAL = eINSTANCE.getCompExpression_Real();

    /**
     * The meta object literal for the '<em><b>Imag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMP_EXPRESSION__IMAG = eINSTANCE.getCompExpression_Imag();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolExpressionImpl <em>Bool Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.BoolExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolExpression()
     * @generated
     */
    EClass BOOL_EXPRESSION = eINSTANCE.getBoolExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.BoolConstantImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolNumCompExpressionImpl <em>Bool Num Comp Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.BoolNumCompExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolNumCompExpression()
     * @generated
     */
    EClass BOOL_NUM_COMP_EXPRESSION = eINSTANCE.getBoolNumCompExpression();

    /**
     * The meta object literal for the '<em><b>Comp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_NUM_COMP_EXPRESSION__COMP = eINSTANCE.getBoolNumCompExpression_Comp();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_NUM_COMP_EXPRESSION__E1 = eINSTANCE.getBoolNumCompExpression_E1();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_NUM_COMP_EXPRESSION__E2 = eINSTANCE.getBoolNumCompExpression_E2();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.BoolCompExpressionImpl <em>Bool Comp Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.BoolCompExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getBoolCompExpression()
     * @generated
     */
    EClass BOOL_COMP_EXPRESSION = eINSTANCE.getBoolCompExpression();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_COMP_EXPRESSION__E1 = eINSTANCE.getBoolCompExpression_E1();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_COMP_EXPRESSION__E2 = eINSTANCE.getBoolCompExpression_E2();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.StrExpressionImpl <em>Str Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.StrExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrExpression()
     * @generated
     */
    EClass STR_EXPRESSION = eINSTANCE.getStrExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STR_EXPRESSION__VALUE = eINSTANCE.getStrExpression_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ListExpressionImpl <em>List Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ListExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getListExpression()
     * @generated
     */
    EClass LIST_EXPRESSION = eINSTANCE.getListExpression();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_EXPRESSION__ARGS = eINSTANCE.getListExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.PrintExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getPrintExpression()
     * @generated
     */
    EClass PRINT_EXPRESSION = eINSTANCE.getPrintExpression();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT_EXPRESSION__EXPR = eINSTANCE.getPrintExpression_Expr();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ListOpExpressionImpl <em>List Op Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ListOpExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getListOpExpression()
     * @generated
     */
    EClass LIST_OP_EXPRESSION = eINSTANCE.getListOpExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.CarExpressionImpl <em>Car Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.CarExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCarExpression()
     * @generated
     */
    EClass CAR_EXPRESSION = eINSTANCE.getCarExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAR_EXPRESSION__LIST = eINSTANCE.getCarExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.CdrExpressionImpl <em>Cdr Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.CdrExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getCdrExpression()
     * @generated
     */
    EClass CDR_EXPRESSION = eINSTANCE.getCdrExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDR_EXPRESSION__LIST = eINSTANCE.getCdrExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.LengthExpressionImpl <em>Length Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.LengthExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getLengthExpression()
     * @generated
     */
    EClass LENGTH_EXPRESSION = eINSTANCE.getLengthExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LENGTH_EXPRESSION__LIST = eINSTANCE.getLengthExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.EmptyExpressionImpl <em>Empty Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.EmptyExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getEmptyExpression()
     * @generated
     */
    EClass EMPTY_EXPRESSION = eINSTANCE.getEmptyExpression();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMPTY_EXPRESSION__LIST = eINSTANCE.getEmptyExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ConsExpressionImpl <em>Cons Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ConsExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getConsExpression()
     * @generated
     */
    EClass CONS_EXPRESSION = eINSTANCE.getConsExpression();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONS_EXPRESSION__EXPR = eINSTANCE.getConsExpression_Expr();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONS_EXPRESSION__LIST = eINSTANCE.getConsExpression_List();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.StrOpExpressionImpl <em>Str Op Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.StrOpExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrOpExpression()
     * @generated
     */
    EClass STR_OP_EXPRESSION = eINSTANCE.getStrOpExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.StrLenExpressionImpl <em>Str Len Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.StrLenExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrLenExpression()
     * @generated
     */
    EClass STR_LEN_EXPRESSION = eINSTANCE.getStrLenExpression();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STR_LEN_EXPRESSION__STR = eINSTANCE.getStrLenExpression_Str();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl <em>Str App Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.StrAppExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getStrAppExpression()
     * @generated
     */
    EClass STR_APP_EXPRESSION = eINSTANCE.getStrAppExpression();

    /**
     * The meta object literal for the '<em><b>Str1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STR_APP_EXPRESSION__STR1 = eINSTANCE.getStrAppExpression_Str1();

    /**
     * The meta object literal for the '<em><b>Str2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STR_APP_EXPRESSION__STR2 = eINSTANCE.getStrAppExpression_Str2();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ParamCallExpressionImpl <em>Param Call Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ParamCallExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getParamCallExpression()
     * @generated
     */
    EClass PARAM_CALL_EXPRESSION = eINSTANCE.getParamCallExpression();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_CALL_EXPRESSION__PARAM = eINSTANCE.getParamCallExpression_Param();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.ArithExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getArithExpression()
     * @generated
     */
    EClass ARITH_EXPRESSION = eINSTANCE.getArithExpression();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITH_EXPRESSION__OP = eINSTANCE.getArithExpression_Op();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__ARG1 = eINSTANCE.getArithExpression_Arg1();

    /**
     * The meta object literal for the '<em><b>Oargs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__OARGS = eINSTANCE.getArithExpression_Oargs();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.IfExpressionImpl <em>If Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.IfExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getIfExpression()
     * @generated
     */
    EClass IF_EXPRESSION = eINSTANCE.getIfExpression();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__COND = eINSTANCE.getIfExpression_Cond();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__THEN = eINSTANCE.getIfExpression_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_EXPRESSION__ELSE = eINSTANCE.getIfExpression_Else();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.FunctionCallExpressionImpl <em>Function Call Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.FunctionCallExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getFunctionCallExpression()
     * @generated
     */
    EClass FUNCTION_CALL_EXPRESSION = eINSTANCE.getFunctionCallExpression();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__FUNCTION = eINSTANCE.getFunctionCallExpression_Function();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_EXPRESSION__ARGS = eINSTANCE.getFunctionCallExpression_Args();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.losCheetos.impl.WhileExpressionImpl <em>While Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.losCheetos.impl.WhileExpressionImpl
     * @see edu.upb.lp.isc.losCheetos.impl.LosCheetosPackageImpl#getWhileExpression()
     * @generated
     */
    EClass WHILE_EXPRESSION = eINSTANCE.getWhileExpression();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__COND = eINSTANCE.getWhileExpression_Cond();

    /**
     * The meta object literal for the '<em><b>Do</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__DO = eINSTANCE.getWhileExpression_Do();

  }

} //LosCheetosPackage
