/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str App Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr1 <em>Str1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr2 <em>Str2</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrAppExpression()
 * @model
 * @generated
 */
public interface StrAppExpression extends StrOpExpression
{
  /**
   * Returns the value of the '<em><b>Str1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str1</em>' containment reference.
   * @see #setStr1(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrAppExpression_Str1()
   * @model containment="true"
   * @generated
   */
  Expression getStr1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr1 <em>Str1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str1</em>' containment reference.
   * @see #getStr1()
   * @generated
   */
  void setStr1(Expression value);

  /**
   * Returns the value of the '<em><b>Str2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str2</em>' containment reference.
   * @see #setStr2(Expression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrAppExpression_Str2()
   * @model containment="true"
   * @generated
   */
  Expression getStr2();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.StrAppExpression#getStr2 <em>Str2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str2</em>' containment reference.
   * @see #getStr2()
   * @generated
   */
  void setStr2(Expression value);

} // StrAppExpression
