/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str Len Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.StrLenExpression#getStr <em>Str</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrLenExpression()
 * @model
 * @generated
 */
public interface StrLenExpression extends StrOpExpression
{
  /**
   * Returns the value of the '<em><b>Str</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' containment reference.
   * @see #setStr(StrExpression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrLenExpression_Str()
   * @model containment="true"
   * @generated
   */
  StrExpression getStr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.StrLenExpression#getStr <em>Str</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' containment reference.
   * @see #getStr()
   * @generated
   */
  void setStr(StrExpression value);

} // StrLenExpression
