/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str Op Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getStrOpExpression()
 * @model
 * @generated
 */
public interface StrOpExpression extends SimpleExpression
{
} // StrOpExpression
