/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.losCheetos;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.losCheetos.WhileExpression#getCond <em>Cond</em>}</li>
 *   <li>{@link edu.upb.lp.isc.losCheetos.WhileExpression#getDo <em>Do</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getWhileExpression()
 * @model
 * @generated
 */
public interface WhileExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(BoolExpression)
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getWhileExpression_Cond()
   * @model containment="true"
   * @generated
   */
  BoolExpression getCond();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.losCheetos.WhileExpression#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(BoolExpression value);

  /**
   * Returns the value of the '<em><b>Do</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.losCheetos.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Do</em>' containment reference list.
   * @see edu.upb.lp.isc.losCheetos.LosCheetosPackage#getWhileExpression_Do()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getDo();

} // WhileExpression
