/**
 * generated by Xtext 2.11.0
 */
package edu.upb.lp.isc.ui;

import edu.upb.lp.isc.ui.AbstractLosCheetosUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LosCheetosUiModule extends AbstractLosCheetosUiModule {
  public LosCheetosUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
